# Generated by Django 3.1.3 on 2023-06-12 01:01

from django.db import migrations, models
import embed_video.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(blank=True, null=True, verbose_name='app_id')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('genre', models.CharField(max_length=100, verbose_name='genre')),
                ('developer', models.CharField(max_length=100, verbose_name='developer')),
                ('release_at', models.DateTimeField(verbose_name='release Day')),
                ('info', models.TextField(verbose_name='info')),
                ('video', embed_video.fields.EmbedVideoField(null=True)),
                ('thumnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='thumbnail')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genre_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_list', models.CharField(max_length=100, verbose_name='genre_list')),
            ],
        ),
    ]
